### ISSUE TITLE
Migrate to the 6to5 org

### ISSUE THREAD

**Issue by sebmck** [6to5/ember-cli-6to5#9]
Hey @gordonkristan, awesome job on `ember-cli-6to5`! Would you like for it to be migrated over to the 6to5 org? Feel free to decline, just wanted to thank you for taking the time to maintain this, thanks!

**Comment by gordonkristan** [comment]
I don't really mind, since I don't have much time these days to maintain it. As long as there are no potential issues for Ember CLI users, I'll transfer it over. Just one question, will @stefanpenner still have collaborator access to it? Because Ember CLI uses this by default, I'm going to assume that he will need access in case of urgent bugfixes and whatnot.

Also, @stefanpenner, is there anything that I need to do before transferring ownership? Change some NPM settings or something like that?

**Comment by stefanpenner** [comment]
@gordonkristan I actually already have commit to everything on 6to5, so I will still continue to have access. It should be as simple as transferring ownership, and adding sebmck as a npm owner.

@sebmck by sure to give @gordonkristan commit to the new repo once transferred. I would love to keep him on as a maintainer/original author.

**Comment by sebmck** [comment]
@stefanpenner Sure thing, I've added @gordonkristan to the org.

**Comment by gordonkristan** [comment]
I moved the repo over now. Just one last question: I want to update the `package.json` file to point to the right repo, should I edit it directly or open a pull request?

**Comment by sebmck** [comment]
@gordonkristan The project/repo is still completely yours. Feel free to continue as if it was in your user repo.

**Comment by sebmck** [comment]
@gordonkristan Thank you though! I think it's awesome that 6to5 has such a good and consistent plugin ecosystem instead of something fragmented and varying in quality.

**Comment by gordonkristan** [comment]
Yes, I can definitely see the value of having everything in one place, so I'm happy to help. I'm going to use this as opportunity to jump into the 6to5 source code a bit, as it's interested me for a while. You might see some pull requests from me soon. :)

**Comment by sebmck** [comment]
@gordonkristan Great! Let me know if you need any help.
